version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: latte
      DB_PASSWORD: latte
      DB_NAME: frappuccino
      DB_PORT: 5432
      S3_ENDPOINT: http://triple-s:9000
    depends_on:
      - db
      - triple-s

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: latte
      POSTGRES_PASSWORD: latte
      POSTGRES_DB: frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  triple-s:
    build:
      context: ./triple-s
    ports:
     - "9000:9000"
    volumes:
     - ./triple-s/data:/data